package com.mmall.dao;

import com.mmall.pojo.Category;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    @Delete({
            "delete from mmall_category",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    @Insert({
            "insert into mmall_category (id, parent_id, ",
            "name, status, sort_order, ",
            "create_time, update_time)",
            "values (#{id,jdbcType=INTEGER}, #{parentId,jdbcType=INTEGER}, ",
            "#{name,jdbcType=VARCHAR}, #{status,jdbcType=BIT}, #{sortOrder,jdbcType=INTEGER}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    @Select({
            "select",
            "id, parent_id, name, status, sort_order, create_time, update_time",
            "from mmall_category",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mmall.dao.CategoryMapper.BaseResultMap")
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Thu Sep 05 20:20:58 CST 2019
     */
    @Update({
            "update mmall_category",
            "set parent_id = #{parentId,jdbcType=INTEGER},",
            "name = #{name,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=BIT},",
            "sort_order = #{sortOrder,jdbcType=INTEGER},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Category record);

    List<Category> selectCategoryChildrenByParentId(Integer parentId);
}