package com.mmall.dao;

import com.mmall.pojo.OrderItem;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    @Delete({
            "delete from mmall_order_item",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    @Insert({
            "insert into mmall_order_item (id, order_no, ",
            "user_id, product_id, ",
            "product_name, product_image, ",
            "current_unit_price, total_price, ",
            "quantity, payment_time, ",
            "send_time, end_time, ",
            "close_time, create_time, ",
            "update_time)",
            "values (#{id,jdbcType=INTEGER}, #{orderNo,jdbcType=BIGINT}, ",
            "#{userId,jdbcType=INTEGER}, #{productId,jdbcType=INTEGER}, ",
            "#{productName,jdbcType=VARCHAR}, #{productImage,jdbcType=VARCHAR}, ",
            "#{currentUnitPrice,jdbcType=DECIMAL}, #{totalPrice,jdbcType=DECIMAL}, ",
            "#{quantity,jdbcType=INTEGER}, #{paymentTime,jdbcType=TIMESTAMP}, ",
            "#{sendTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
            "#{closeTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    @Select({
            "select",
            "id, order_no, user_id, product_id, product_name, product_image, current_unit_price, ",
            "total_price, quantity, payment_time, send_time, end_time, close_time, create_time, ",
            "update_time",
            "from mmall_order_item",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mmall.dao.OrderItemMapper.BaseResultMap")
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Mon Sep 09 20:05:02 CST 2019
     */
    @Update({
            "update mmall_order_item",
            "set order_no = #{orderNo,jdbcType=BIGINT},",
            "user_id = #{userId,jdbcType=INTEGER},",
            "product_id = #{productId,jdbcType=INTEGER},",
            "product_name = #{productName,jdbcType=VARCHAR},",
            "product_image = #{productImage,jdbcType=VARCHAR},",
            "current_unit_price = #{currentUnitPrice,jdbcType=DECIMAL},",
            "total_price = #{totalPrice,jdbcType=DECIMAL},",
            "quantity = #{quantity,jdbcType=INTEGER},",
            "payment_time = #{paymentTime,jdbcType=TIMESTAMP},",
            "send_time = #{sendTime,jdbcType=TIMESTAMP},",
            "end_time = #{endTime,jdbcType=TIMESTAMP},",
            "close_time = #{closeTime,jdbcType=TIMESTAMP},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderItem record);

    //批量插入
    void batchInsert(@Param("orderItemList") List<OrderItem> orderItemList);

    List<OrderItem> selectByUserIdOrderNo(@Param("userId") Integer userId, @Param("orderNo") Long orderNo);
}