package com.mmall.dao;

import com.mmall.pojo.Product;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    @Delete({
            "delete from mmall_product",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    @Insert({
            "insert into mmall_product (id, category_id, ",
            "name, subtitle, ",
            "main_image, sub_images, ",
            "detail, price, stock, ",
            "status, create_time, ",
            "update_time)",
            "values (#{id,jdbcType=INTEGER}, #{categoryId,jdbcType=INTEGER}, ",
            "#{name,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
            "#{mainImage,jdbcType=VARCHAR}, #{subImages,jdbcType=VARCHAR}, ",
            "#{detail,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, #{stock,jdbcType=INTEGER}, ",
            "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    @Select({
            "select",
            "id, category_id, name, subtitle, main_image, sub_images, detail, price, stock, ",
            "status, create_time, update_time",
            "from mmall_product",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mmall.dao.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    @Update({
            "update mmall_product",
            "set category_id = #{categoryId,jdbcType=INTEGER},",
            "name = #{name,jdbcType=VARCHAR},",
            "subtitle = #{subtitle,jdbcType=VARCHAR},",
            "main_image = #{mainImage,jdbcType=VARCHAR},",
            "sub_images = #{subImages,jdbcType=VARCHAR},",
            "detail = #{detail,jdbcType=VARCHAR},",
            "price = #{price,jdbcType=DECIMAL},",
            "stock = #{stock,jdbcType=INTEGER},",
            "status = #{status,jdbcType=INTEGER},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);

    List<Product> selectList();

    List<Product> selectByNameAndProductId(@Param("productName") String productName,
                                           @Param("productId") int productId);
}