package com.mmall.dao;

import com.mmall.pojo.Shipping;
import org.apache.ibatis.annotations.*;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    @Delete({
            "delete from mmall_shipping",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    @Insert({
            "insert into mmall_shipping (id, user_id, ",
            "receiver_name, receiver_phone, ",
            "receiver_mobile, receiver_province, ",
            "receiver_city, receiver_district, ",
            "receiver_address, receiver_zip, ",
            "create_time, update_time)",
            "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
            "#{receiverName,jdbcType=VARCHAR}, #{receiverPhone,jdbcType=VARCHAR}, ",
            "#{receiverMobile,jdbcType=VARCHAR}, #{receiverProvince,jdbcType=VARCHAR}, ",
            "#{receiverCity,jdbcType=VARCHAR}, #{receiverDistrict,jdbcType=VARCHAR}, ",
            "#{receiverAddress,jdbcType=VARCHAR}, #{receiverZip,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    @Select({
            "select",
            "id, user_id, receiver_name, receiver_phone, receiver_mobile, receiver_province, ",
            "receiver_city, receiver_district, receiver_address, receiver_zip, create_time, ",
            "update_time",
            "from mmall_shipping",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.mmall.dao.ShippingMapper.BaseResultMap")
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Sat Sep 07 21:04:10 CST 2019
     */
    @Update({
            "update mmall_shipping",
            "set user_id = #{userId,jdbcType=INTEGER},",
            "receiver_name = #{receiverName,jdbcType=VARCHAR},",
            "receiver_phone = #{receiverPhone,jdbcType=VARCHAR},",
            "receiver_mobile = #{receiverMobile,jdbcType=VARCHAR},",
            "receiver_province = #{receiverProvince,jdbcType=VARCHAR},",
            "receiver_city = #{receiverCity,jdbcType=VARCHAR},",
            "receiver_district = #{receiverDistrict,jdbcType=VARCHAR},",
            "receiver_address = #{receiverAddress,jdbcType=VARCHAR},",
            "receiver_zip = #{receiverZip,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Shipping record);

    int deleteByUserIdShippingId(@Param("userId") Integer userId, @Param("shippingId") Integer shippingId);
}