package com.mmall.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.id
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.order_no
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.user_id
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.product_id
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.product_name
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.product_image
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.current_unit_price
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private BigDecimal currentUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.quantity
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.payment_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.send_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.end_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.close_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.create_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_order_item.update_time
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem(Integer id, Long orderNo, Integer userId, Integer productId, String productName, String productImage, BigDecimal currentUnitPrice, Integer quantity, Date paymentTime, Date sendTime, Date endTime, Date closeTime, Date createTime, Date updateTime) {
        this.id = id;
        this.orderNo = orderNo;
        this.userId = userId;
        this.productId = productId;
        this.productName = productName;
        this.productImage = productImage;
        this.currentUnitPrice = currentUnitPrice;
        this.quantity = quantity;
        this.paymentTime = paymentTime;
        this.sendTime = sendTime;
        this.endTime = endTime;
        this.closeTime = closeTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.id
     *
     * @return the value of mmall_order_item.id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.id
     *
     * @param id the value for mmall_order_item.id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.order_no
     *
     * @return the value of mmall_order_item.order_no
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withOrderNo(Long orderNo) {
        this.setOrderNo(orderNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.order_no
     *
     * @param orderNo the value for mmall_order_item.order_no
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.user_id
     *
     * @return the value of mmall_order_item.user_id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.user_id
     *
     * @param userId the value for mmall_order_item.user_id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.product_id
     *
     * @return the value of mmall_order_item.product_id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withProductId(Integer productId) {
        this.setProductId(productId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.product_id
     *
     * @param productId the value for mmall_order_item.product_id
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.product_name
     *
     * @return the value of mmall_order_item.product_name
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withProductName(String productName) {
        this.setProductName(productName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.product_name
     *
     * @param productName the value for mmall_order_item.product_name
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.product_image
     *
     * @return the value of mmall_order_item.product_image
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withProductImage(String productImage) {
        this.setProductImage(productImage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.product_image
     *
     * @param productImage the value for mmall_order_item.product_image
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.current_unit_price
     *
     * @return the value of mmall_order_item.current_unit_price
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.setCurrentUnitPrice(currentUnitPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.current_unit_price
     *
     * @param currentUnitPrice the value for mmall_order_item.current_unit_price
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.quantity
     *
     * @return the value of mmall_order_item.quantity
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withQuantity(Integer quantity) {
        this.setQuantity(quantity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.quantity
     *
     * @param quantity the value for mmall_order_item.quantity
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.payment_time
     *
     * @return the value of mmall_order_item.payment_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withPaymentTime(Date paymentTime) {
        this.setPaymentTime(paymentTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.payment_time
     *
     * @param paymentTime the value for mmall_order_item.payment_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.send_time
     *
     * @return the value of mmall_order_item.send_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withSendTime(Date sendTime) {
        this.setSendTime(sendTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.send_time
     *
     * @param sendTime the value for mmall_order_item.send_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.end_time
     *
     * @return the value of mmall_order_item.end_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withEndTime(Date endTime) {
        this.setEndTime(endTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.end_time
     *
     * @param endTime the value for mmall_order_item.end_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.close_time
     *
     * @return the value of mmall_order_item.close_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withCloseTime(Date closeTime) {
        this.setCloseTime(closeTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.close_time
     *
     * @param closeTime the value for mmall_order_item.close_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.create_time
     *
     * @return the value of mmall_order_item.create_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.create_time
     *
     * @param createTime the value for mmall_order_item.create_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_order_item.update_time
     *
     * @return the value of mmall_order_item.update_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public OrderItem withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_order_item.update_time
     *
     * @param updateTime the value for mmall_order_item.update_time
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbg.generated Sun Sep 08 16:12:12 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productImage=").append(productImage);
        sb.append(", currentUnitPrice=").append(currentUnitPrice);
        sb.append(", quantity=").append(quantity);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}