package com.mmall.pojo;

import java.io.Serializable;
import java.util.Date;

public class PayInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.id
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.user_id
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.order_no
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.pay_platform
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Integer payPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.platform_number
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private String platformNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.platform_status
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private String platformStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.create_time
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_pay_info.update_time
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo(Integer id, Integer userId, Long orderNo, Integer payPlatform, String platformNumber, String platformStatus, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.orderNo = orderNo;
        this.payPlatform = payPlatform;
        this.platformNumber = platformNumber;
        this.platformStatus = platformStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.id
     *
     * @return the value of mmall_pay_info.id
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.id
     *
     * @param id the value for mmall_pay_info.id
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.user_id
     *
     * @return the value of mmall_pay_info.user_id
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.user_id
     *
     * @param userId the value for mmall_pay_info.user_id
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.order_no
     *
     * @return the value of mmall_pay_info.order_no
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withOrderNo(Long orderNo) {
        this.setOrderNo(orderNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.order_no
     *
     * @param orderNo the value for mmall_pay_info.order_no
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.pay_platform
     *
     * @return the value of mmall_pay_info.pay_platform
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withPayPlatform(Integer payPlatform) {
        this.setPayPlatform(payPlatform);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.pay_platform
     *
     * @param payPlatform the value for mmall_pay_info.pay_platform
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.platform_number
     *
     * @return the value of mmall_pay_info.platform_number
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withPlatformNumber(String platformNumber) {
        this.setPlatformNumber(platformNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.platform_number
     *
     * @param platformNumber the value for mmall_pay_info.platform_number
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.platform_status
     *
     * @return the value of mmall_pay_info.platform_status
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withPlatformStatus(String platformStatus) {
        this.setPlatformStatus(platformStatus);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.platform_status
     *
     * @param platformStatus the value for mmall_pay_info.platform_status
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus == null ? null : platformStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.create_time
     *
     * @return the value of mmall_pay_info.create_time
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.create_time
     *
     * @param createTime the value for mmall_pay_info.create_time
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_pay_info.update_time
     *
     * @return the value of mmall_pay_info.update_time
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public PayInfo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_pay_info.update_time
     *
     * @param updateTime the value for mmall_pay_info.update_time
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Sun Sep 08 13:21:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", payPlatform=").append(payPlatform);
        sb.append(", platformNumber=").append(platformNumber);
        sb.append(", platformStatus=").append(platformStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}