package com.mmall.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.id
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.category_id
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.name
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.subtitle
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.main_image
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.sub_images
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private String subImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.detail
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.price
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.stock
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.status
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.create_time
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_product.update_time
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product(Integer id, Integer categoryId, String name, String subtitle, String mainImage, String subImages, String detail, BigDecimal price, Integer stock, Integer status, Date createTime, Date updateTime) {
        this.id = id;
        this.categoryId = categoryId;
        this.name = name;
        this.subtitle = subtitle;
        this.mainImage = mainImage;
        this.subImages = subImages;
        this.detail = detail;
        this.price = price;
        this.stock = stock;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.id
     *
     * @return the value of mmall_product.id
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.id
     *
     * @param id the value for mmall_product.id
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.category_id
     *
     * @return the value of mmall_product.category_id
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withCategoryId(Integer categoryId) {
        this.setCategoryId(categoryId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.category_id
     *
     * @param categoryId the value for mmall_product.category_id
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.name
     *
     * @return the value of mmall_product.name
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.name
     *
     * @param name the value for mmall_product.name
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.subtitle
     *
     * @return the value of mmall_product.subtitle
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withSubtitle(String subtitle) {
        this.setSubtitle(subtitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.subtitle
     *
     * @param subtitle the value for mmall_product.subtitle
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.main_image
     *
     * @return the value of mmall_product.main_image
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withMainImage(String mainImage) {
        this.setMainImage(mainImage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.main_image
     *
     * @param mainImage the value for mmall_product.main_image
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.sub_images
     *
     * @return the value of mmall_product.sub_images
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withSubImages(String subImages) {
        this.setSubImages(subImages);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.sub_images
     *
     * @param subImages the value for mmall_product.sub_images
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.detail
     *
     * @return the value of mmall_product.detail
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withDetail(String detail) {
        this.setDetail(detail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.detail
     *
     * @param detail the value for mmall_product.detail
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.price
     *
     * @return the value of mmall_product.price
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withPrice(BigDecimal price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.price
     *
     * @param price the value for mmall_product.price
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.stock
     *
     * @return the value of mmall_product.stock
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withStock(Integer stock) {
        this.setStock(stock);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.stock
     *
     * @param stock the value for mmall_product.stock
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.status
     *
     * @return the value of mmall_product.status
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.status
     *
     * @param status the value for mmall_product.status
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.create_time
     *
     * @return the value of mmall_product.create_time
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.create_time
     *
     * @param createTime the value for mmall_product.create_time
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_product.update_time
     *
     * @return the value of mmall_product.update_time
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public Product withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_product.update_time
     *
     * @param updateTime the value for mmall_product.update_time
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbg.generated Fri Sep 06 20:55:33 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", name=").append(name);
        sb.append(", subtitle=").append(subtitle);
        sb.append(", mainImage=").append(mainImage);
        sb.append(", subImages=").append(subImages);
        sb.append(", detail=").append(detail);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}